### ISSUE TITLE
скачивает пустые файлы

### ISSUE THREAD

**Issue by nkulbaka** [badbob/elib-dl#1]
Вот ссылка на книгу, которую не могу скачать

http://elib.shpl.ru/ru/nodes/19462#mode/inspect/page/1/zoom/4

**Comment by badbob** [comment]
Похоже, что на сайте было проведено обновление с целью отсечь тех, кто скачивает книги. 
В новой версии утилиты это ограничение обойдено. 

Попробуйте скачать [версию 0.5](https://github.com/badbob/elib-dl/releases/download/0.5/elib-dl.exe). Напишите сюда, если не будет работать. (Версия 0.5 собрана под Wine, поэтому косяки не исключены)

**Comment by Melor333** [comment]
До этого все работало нормально, а потом начались пустые файлы. К сожалению, версия 0.5 тоже не работает. Пишет:
```
Error loading Python DLL 'C:\Users\STEELR~1\AppData\Local\Temp\_MEI29602\python3
4.dll'.
No error messages generated.
FormatMessageW: ╧рЁрьхЄЁ чрфрэ эхтхЁэю.
LoadLibrary: PyInstaller: FormatMessageW failed.
```

**Comment by Dieseng** [comment]
Доброго времени суток. Ругается на 10-ю строку.
Traceback (most recent call last):
  File "elib-dl.py", line 10, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

**Comment by denis702** [comment]
badbob, спасибо за программку! с сожалением подтверждаю оба поста выше. новая качает файлы 0b а старая дает такой ответ как приведено ниже. Библиотека питон34 нужна? где взять? Спасибо!

Microsoft Windows [Version 10.0.18363.778]
(c) Корпорация Майкрософт (Microsoft Corporation), 2019. Все права защищены.

C:\Users\Acer-new>C:\Users\Acer-new\Downloads\elib-dlold.exe http://elib.shpl.ru/ru/nodes/56531-sklad-ee-imperatorskogo-velichestva-gosudaryni-imperatritsy-aleksandry-fedorovny-v-moskve-dlya-ranenyh-i-bolnyh-voinov-i-dlya-deystvuyuschey-armii-godovoy-otchet-26-iyulya-1914-g-1-e-iyulya-1915-g-m-1915
Error loading Python DLL 'C:\Users\Acer-new\AppData\Local\Temp\_MEI101162\python34.dll'.
No error messages generated.
FormatMessageW: ╧рЁрьхЄЁ чрфрэ эхтхЁэю.
LoadLibrary: PyInstaller: FormatMessageW failed.
C:\Users\Acer-new>

**Comment by badbob** [comment]
@denis702 
К сожалению, я не могу собрать исполняемый EXE-файл. Мне нужна для этого помощь человека, у которого есть Windows-машина. 
Если вы готовы мне помочь, свяжитесь со мной в VK или по почте. 
Или же запускайте утилиту при помощи интерпретатора Python.

**Comment by denis702** [comment]
Vladimir Loshchin | Vladimir Loshchin
-- | --
Vladimir Loshchin не найден в ВК, как Вас там найти?

**Comment by badbob** [comment]
@denis702 [мой профиль в ВК](https://vk.com/6adbob)

**Comment by denis702** [comment]
меня там заблокировали до 10.05(

пт, 1 мая 2020 г. в 06:05, Vladimir Loshchin <notifications@github.com>:

**Comment by badbob** [comment]
Попробуйте версию 0.6. [Ссылка для скачивания](https://github.com/badbob/elib-dl/releases/download/v0.6/elib-dl.exe)
