### ISSUE TITLE
ошибка

### ISSUE THREAD

**Issue by kalinina33** [badbob/elib-dl#3]
![D1B6DB9A-5279-4FA4-A926-06367CFBF74A](https://user-images.githubusercontent.com/65895344/82799976-3e096780-9ebe-11ea-909a-06fac1d8cd96.jpeg)

Помогите, не понимаю, что нужно делать. 
Приходилось гуглить некоторые шаги, так как в инструкции ничего не понятно. Как запустить, как скачать? Объясните, пожалуйста.

**Comment by badbob** [comment]
Здравсвуйте. Попробуйте версию 0.6 у EXE. [Ссылка для скачивания](https://github.com/badbob/elib-dl/releases/download/v0.6/elib-dl.exe).
